# Default values for dbdump.

image:
  # -- image repository
  repository: djjudas21/dbdump
  # -- image tag
  # @default -- chart.appVersion
  tag: ""
  # -- image pull policy
  pullPolicy: IfNotPresent

imagePullSecrets: []

nameOverride: ""
fullnameOverride: ""

databases:
## Without a host set, this chart will not do anything as it is expected
## to be used only when there's an existing database to backup.
## The hostname must also be unique for each backup job.
- host: "example.com"
  # -- Database type, mysql or postgresql
  type: ""
  # -- username
  username: "root"
  # -- password
  password: ""
  port: "3306"
  # -- db name for single db backup
  database: ""
  # -- use --all-databases if enabled
  allDatabases: "true"
  # -- debug output
  debug: "false"
  # -- schedule override
  schedule: ""

# -- options to pass to mysqldump
mysqldumpOptions: "--single-transaction"

# -- options to pass to pgdump
pgdumpOptions: ""

# -- cron time setting for backup schedule
schedule: "0 3 * * *"

# -- cronjob history
successfulJobsHistoryLimit: 3
failedJobsHistoryLimit: 3

## set persistentVolumeClaim to use a PVC that already exists.
## if set will override any settings under `persistence` otherwise
## if not set and `persistence.enabled` set to true, will create a PVC.
# persistentVolumeClaim: <existing-PVC>

podAnnotations: {}

persistence:
  enabled: true
  size: 8Gi
  accessMode: ReadWriteMany
  subPath:
  ## If defined, storageClassName: <storageClass>
  ## If set to "-", storageClassName: "", which disables dynamic provisioning
  ## If undefined (the default) or set to null, no storageClassName spec is
  ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
  ##   GKE, AWS & OpenStack)
  ##
  # storageClass: "-"

# -- delete old backups
housekeeping:
  enabled: true
  keepDays: 10

resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

# -- Pod Security Context
securityContext:
  enabled: false
  fsGroup: 999
  runAsUser: 999

# -- dependency chart for ci
mariadb:
  enabled: false
