apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "reactive-resume.nameClient" . }}
  labels:
    {{- include "reactive-resume.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.client.replicaCount }}
  selector:
    matchLabels:
      {{- include "reactive-resume.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.client.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "reactive-resume.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.client.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "reactive-resume.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.client.podSecurityContext | nindent 8 }}
      containers:
        - name: client
          env:
            - name: PUBLIC_GOOGLE_CLIENT_ID
              value: {{ .Values.config.google.clientId }}
            {{- if .Values.ingress.enabled }}
            - name: PUBLIC_SERVER_URL
              value: {{ .Values.config.publicServerUrl }}
            - name: PUBLIC_URL
              value: {{ .Values.config.publicUrl }}
            {{- else }}
            - name: PUBLIC_SERVER_URL
              value: {{ .Values.config.publicServerUrl }}
            - name: PUBLIC_URL
              value: {{ .Values.config.publicUrl }}
            {{- end }}
          securityContext:
            {{- toYaml .Values.client.securityContext | nindent 12 }}
          image: "{{ .Values.client.image.repository }}:{{ include "reactive-resume.clientImageTag" . }}"
          imagePullPolicy: {{ .Values.client.image.pullPolicy }}
          ports:
            - name: client
              containerPort: {{ .Values.client.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: client
          readinessProbe:
            httpGet:
              path: /
              port: client
          resources:
            {{- toYaml .Values.client.resources | nindent 12 }}
      {{- with .Values.client.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.client.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.client.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
