apiVersion: v1
kind: Service
metadata:
  name: {{ include "reactive-resume.nameClient" . }}
  labels:
    {{- include "reactive-resume.labels" . | nindent 4 }}
spec:
  type: {{ .Values.client.service.type }}
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    {{- include "reactive-resume.selectorLabelsClient" . | nindent 4 }}
