apiVersion: v1
kind: Service
metadata:
  name: {{ include "reactive-resume.nameServer" . }}
  labels:
    {{- include "reactive-resume.labels" . | nindent 4 }}
spec:
  type: {{ .Values.server.service.type }}
  ports:
    - port: {{ .Values.server.service.port }}
      targetPort: {{ .Values.server.service.port }}
      protocol: TCP
      #name: http
  selector:
    {{- include "reactive-resume.selectorLabelsServer" . | nindent 4 }}
