apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "lldap.fullname" . }}-data
  labels:
    {{- include "lldap.labels" . | nindent 4 }}
  storageClassName: {{ .Values.persistence.storageClass }}
  accessModes:
    - {{ .Values.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
