kind: Secret
apiVersion: v1
type: Opaque
metadata:
  name: {{ include "lldap.fullname" . }}-credentials
data:
  base-dn: {{ .Values.lldap.base-dn | b64enc }}
  jwt-secret: {{ .Values.lldap.jwt-secret | b64enc }}
  ldap-user-pass: {{ .Values.lldap.ldap-user-pass | b64enc }}
