kind: Secret
apiVersion: v1
type: Opaque
metadata:
  name: {{ include "lldap.fullname" . }}-credentials
data:
  baseDN: {{ .Values.lldap.baseDN | b64enc }}
  jwtSecret: {{ .Values.lldap.jwtSecret | b64enc }}
  ldapUserPass: {{ .Values.lldap.ldapUserPass | b64enc }}
