---
apiVersion: v2
appVersion: 1.8.0
description: Paperless - Index and archive all of your scanned paper documents
name: paperless
version: 9.2.3
kubeVersion: ">=1.16.0-0"
keywords:
  - paperless
home: https://github.com/djjudas21/charts/tree/master/charts/paperless
icon: https://avatars.githubusercontent.com/u/47271576?s=200&v=4
sources:
  - https://github.com/paperless-ngx/paperless-ngx
maintainers:
  - name: djjudas21
    email: djjudas21@users.noreply.github.com
dependencies:
  - name: common
    repository: http://bjw-s.github.io/helm-charts/
    version: 0.2.0
  - name: postgresql
    version: 11.6.12
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: redis
    version: 16.13.1
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Downgrade to bjw-s/common 0.2.0
