{{- range .Values.mysql }}
{{- if .Values.runDirectlyAfterInstall -}}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .host }}
  labels:
    {{- include "mysqldump.labels" . | nindent 4 }}
spec:
  backoffLimit: 1
  template:
{{- $file := .Files.Get "files/job.tpl" }}
{{ tpl $file . | indent 4 }}
{{ end }}
{{- end }}  
