{{- if and .Values.metrics.enabled .Values.metrics.prometheusRules.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: service-prometheus
    role: alert-rules
  name: {{ include "smtp-relay.fullname" . }}
spec:
  groups:
  - name: smtp-relay.rules
    rules:
{{ .Files.Get "files/prometheus.rules" }}
{{- end }}
