# Default values for smokeping.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

smokeping:
  owner: LinuxServer.io
  contact: admin@linuxserver.io
  database:
    # -- How many seconds between tests
    step: 300
    # -- How many pings to send for each test
    pings: 20
  email:
    to: alertee@address.somewhere
    from: smokealert@company.xy
    # -- The person who gets all mail for userids < 1000. Make this empty to disable rewriting.
    root:
    # -- The place where the mail goes. The actual machine name is required - no
    # MX records are consulted. Commonly mailhosts are named mail.domain.com
    mailhub: smtp.gmail.com:587
    AuthUser:
    AuthPass:
    UseSTARTTLS: yes
    # -- Where will the mail seem to come from?
    rewriteDomain:
    # -- The full hostname
    hostname:
  targets:
    - name: Internet
      menu: Internal Devices
      title: Internal Devices
      hosts:
        - name: Router
          menu: Router
          title: Router
          host: modem.gazeley.lan
        - name: TrueNAS
          menu: TrueNAS
          title: TrueNAS
          host: nas.gazeley.lan
        - name: RaspberryPi
          menu: RaspberryPi
          title: Raspberry Pi
          host: rpi.gazeley.lan
        - name: AP
          menu: AP
          title: AP
          host: ap.gazeley.lan
        - name: uk-west-1
          menu: uk-west-1
          title: uk-west-1
          host: uk-west-1-wifi.gazeley.lan
    - name: VirginMedia
      menu: Virgin Media
      title: Virgin Media
      hosts:
        - name: VirginMediaDNS1
          menu: cache1.service.virginmedia.net
          title: cache1.service.virginmedia.net
          host: 194.168.4.100
        - name: VirginMediaDNS2
          menu: cache2.service.virginmedia.net
          title: cache2.service.virginmedia.net
          host: 194.168.8.100
    - name: InternetSites
      menu: Internet Sites
      title: Internet Sites
      hosts:
        - name: GoogleSearch
          menu: Google
          title: google.com
          host: google.com
        - name: linuxserverio
          menu: linuxserver.io
          title: linuxserver.io
          host: linuxserver.io

    - name: DNSProbes
      menu: DNS Probes
      title: DNS Probes
      probe: DNS
      hosts:
        - name: GoogleDNS1
          menu: Google DNS 1
          title: Google DNS 8.8.8.8
          host: 8.8.8.8
        - name: GoogleDNS2
          menu: Google DNS 2
          title: Google DNS 8.8.4.4
          host: 8.8.4.4
        - name: CloudflareDNS1
          menu: Cloudflare DNS 1
          title: Cloudflare DNS 1.1.1.1
          host: 1.1.1.1
        - name: CloudflareDNS2
          menu: Cloudflare DNS 2
          title: Cloudflare DNS 1.0.0.1
          host: 1.0.0.1
        - name: VirginMediaDNS1
          menu: Virgin Media DNS 1
          title: Virgin Media DNS 194.168.4.100
          host: 194.168.4.100
        - name: VirginMediaDNS2
          menu: Virgin Media DNS 2
          title: Virgin Media DNS 194.168.8.100
          host: 194.168.8.100

replicaCount: 1

image:
  repository: linuxserver/smokeping
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # -- Specifies whether a service account should be created
  create: true
  # -- Automatically mount a ServiceAccount's API credentials?
  automount: false
  # -- Annotations to add to the service account
  annotations: {}
  # -- The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

# -- configure probes
probes:
  liveness:
    enabled: true
    failureThreshold: 3
    initialDelaySeconds: 0
    periodSeconds: 10
    timeoutSeconds: 1
  readiness:
    enabled: true
    failureThreshold: 3
    initialDelaySeconds: 0
    periodSeconds: 10
    timeoutSeconds: 1

persistence:
  enabled: true
  storageClass: ""
  size: "5Gi"
  mountPath: "/data/"
  accessMode: ReadWriteOnce

nodeSelector: {}

tolerations: []

affinity: {}
