{{- range .Values.mysql }}

#mysql:
#  host: ""
#  username: "root"
#  password: ""
#  port: 3306
#  db: ""

{{- if ne .Values.schedule "now" -}}
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .host }}
  labels:
    {{- include "dbdump.labels" . | nindent 4 }}
spec:
  schedule: "{{ .Values.schedule }}"
  successfulJobsHistoryLimit: {{ .Values.successfulJobsHistoryLimit }}
  failedJobsHistoryLimit: {{ .Values.failedJobsHistoryLimit }}
  concurrencyPolicy: Forbid
  jobTemplate:
    metadata:
      labels:
        {{- include "dbdump.labels" . | nindent 8 }}
        cronjob-name: {{ .host }}
    spec:
      backoffLimit: 1
      template:
{{- $file := .Files.Get "files/job.tpl" }}
{{ tpl $file . | indent 8 }}
{{ end }}
{{- end }}
