---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "openssh-server.fullname" . }}-custom-scripts
  labels:
    {{- include "openssh-server.labels" . | nindent 4 }}
data:
  install-packages.bash: |
    #!/bin/bash
    {{- if .Values.packages }}
    apk add --no-cache{{- range .Values.packages }} {{ . }}{{- end }}  
    {{- end }}
