apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "openssh-server.fullname" . }}
  labels:
    {{- include "openssh-server.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "openssh-server.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "openssh-server.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "openssh-server.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: PUID
              value: {{ quote .Values.env.puid }}
            - name: PGID
              value: {{ quote .Values.env.pgid }}
            - name: TZ
              value: {{ quote .Values.env.tz }}
            {{- if .Values.env.publicKey }}
            - name: PUBLIC_KEY
              value: {{ quote .Values.env.publicKey }}
            {{- end }}
            {{- if .Values.env.publicKeyFile }}
            - name: PUBLIC_KEY_FILE
              value: {{ quote .Values.env.publicKeyFile }}
            {{- end }}
            {{- if .Values.env.publicKeyDir }}
            - name: PUBLIC_KEY_DIR
              value: {{ quote .Values.env.publicKeyDir }}
            {{- end }}
            {{- if .Values.env.publicKeyUrl }}
            - name: PUBLIC_KEY_URL
              value: {{ quote .Values.env.publicKeyUrl }}
            {{- end }}
            - name: SUDO_ACCESS
              value: {{ quote .Values.env.sudoAccess }}
            - name: PASSWORD_ACCESS
              value: {{ quote .Values.env.passwordAccess }}
            {{- if .Values.env.userPassword }}
            - name: USER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-password
                  key: USER_PASSWORD
            {{- end }}
            {{- if .Values.env.userPasswordFile }}
            - name: USER_PASSWORD_FILE
              value: {{ quote .Values.env.userPasswordFile }}
            {{- end }}
            {{- if .Values.env.userName }}
            - name: USER_NAME
              value: {{ quote .Values.env.userName }}
            {{- end }}
          ports:
            - name: ssh
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
          {{- if or .Values.persistence.home.enabled .Values.persistence.config.enabled }}
          volumeMounts:
          {{- if .Values.persistence.home.enabled }}
          - mountPath: /root
            name: home
          {{- end }}
          {{- if .Values.persistence.config.enabled }}
          - mountPath: /config
            name: config
          {{- end }}
          {{- end }}
          livenessProbe:
            tcpSocket:
              port: {{ .Values.service.targetPort }}
          readinessProbe:
            tcpSocket:
              port: {{ .Values.service.targetPort }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- if or .Values.persistence.home.enabled .Values.persistence.config.enabled }}
      volumes:
        {{- if .Values.persistence.home.enabled }}
      - name: home
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-home
        {{- end }}
        {{- if .Values.persistence.config.enabled }}
      - name: config
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-config
        {{- end }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
