{{- if .Values.persistence.home.enabled }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-home
  labels:
    {{- include "openssh-server.labels" . | nindent 4 }}
spec:
  {{- if .Values.persistence.home.storageClass }}
  storageClassName: {{ .Values.persistence.home.storageClass }}
  {{- end }}
  accessModes:
  {{- range .Values.persistence.home.accessModes }}
    - {{ . | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.home.size }}
{{- end }}
