{{- if .Values.env.userPassword -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-password
  labels:
    {{- include "openssh-server.labels" . | nindent 4 }}
data:
  USER_PASSWORD: {{ .Values.env.userPassword | b64enc }}
{{- end }}
