# IMPORTANT NOTE
#
# This chart inherits from the k8s@home common library chart. You can check the default values/options here:
# https://github.com/bjw-s/helm-charts/blob/main/charts/library/common/values.yaml
#

image:
  # -- image repository
  repository: alfhou/hammond
  # -- image tag
  tag: ""
  # -- image pull policy
  pullPolicy: IfNotPresent

# -- environment variables. See [image docs](https://docs.kanboard.org/en/latest/admin_guide/docker.html#environment-variables)
# and [application docs](# https://docs.kanboard.org/en/latest/admin_guide/config_file.html) for more details.
# @default -- See below (only deviations from the default settings are specified)
env:
  # Application Configuration
  # -- Application Timezone
  TZ: UTC
  # -- The secret used to sign the JWT token. It is important that you change it to something else
  JWT_SECRET: ChangeMe

# -- Configures service settings for the chart.
# @default -- See values.yaml
service:
  main:
    ports:
      http:
        port: 3000

ingress:
  # -- Enable and configure ingress settings for the chart under this key.
  # @default -- See values.yaml
  main:
    enabled: false

# -- Configure persistence settings for the chart under this key.
# @default -- See values.yaml
persistence:
  config:
    enabled: false
    mountPath: /config
  assets:
    enabled: false
    mountPath: /assets
