apiVersion: v2
name: openssh-server
description: Sandboxed environment that allows ssh access without giving keys to the entire server
type: application
version: 0.1.12
appVersion: "9.6_p1-r0-ls149"

home: https://github.com/djjudas21/charts
icon: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver-ls-icon.png
keywords:
  - ssh
  - openssh
  - bastion
maintainers:
  - name: djjudas21
    email: djjudas21@users.noreply.github.com
sources:
  - https://hub.docker.com/r/linuxserver/openssh-server
  - https://github.com/linuxserver/docker-openssh-server
annotations:
  category: Infrastructure
  artifacthub.io/changes: |-
    - kind: changed
      description: Update OpenSSH image
