{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "nova-exporter.fullname" . }}
  labels:
    {{- include "nova-exporter.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "nova-exporter.labels" . | nindent 6 }}
  endpoints:
  - port: prometheus
    interval: 30s
{{- end }}
